### ISSUE TITLE
change login with code to password instead

### ISSUE THREAD

**Issue by agiraldie** [AlloryDante/Matrix-Rewards-Bot#7]
When login an account with code, change it to Use Password instead
![Screenshot_202](https://github.com/AlloryDante/Matrix-Rewards-Bot/assets/45974979/46b1403d-0877-458c-afea-6be2f7413f65)

**Comment by AlloryDante** [comment]
Um yeah but I dont have a test account and that never showed up to anyone in my Discord community yet.

**Comment by yannikbaranski** [comment]
Bro didn't even Stared the repo 😂

**Comment by AlloryDante** [comment]
Project canceled... Closing all the issues
