### ISSUE TITLE
Script might dont find Browser

### ISSUE THREAD

**Issue by DerMuffin** [AlloryDante/Matrix-Rewards-Bot#8]
Hey There!

First off all... i really like this project. Thanks for your time and effort!

I use Windows 10 22H2 with Chrome Browser that wasnt installed with admin priviledges. In this case it didnt work for me to use the 'auto' 'chrome' or 'manuel' switch to detect the chrome browser.

After execute ChromeSetup with admin rights again, it just works fine. It isnt a real issue but maybe you can add something like that in the readme.

**Comment by AlloryDante** [comment]
Its already there. You can manually specify the chrome path even if its not in the right location. The software just searches for known chrome paths.
